### ISSUE TITLE
Objects are once again not saving when scaled.

### ISSUE THREAD

**Issue by Aarontravess** [EpsilonWoW/Enteleaie#59] opened 2015-07-17 21:02 UTC
Since yesterday night objects have not been saving when scaled correctly. I got bored so I did a little building and it seems that the objects I spawned for the first hour have saved in terms of scale, but the latter half of the building I did hasn't saved scales.

**Comment by timgblack** [comment] 2015-07-18 02:23
Duplicate of #57.

**Closed by timgblack** 2015-07-18 02:23 UTC
Labels: bug, duplicate
