### ISSUE TITLE
Object remains after being deleted

### ISSUE THREAD

**Issue by AddieA** [EpsilonWoW/Enteleaie#45] opened 2015-07-05 09:40 UTC
Attempted to delete an object in my own phase, object is still here, visually and if I use the .go sel command, the object selects. However, if I use the .go scale command on it, I get the "Your selected object is invalid" error.

**Comment by timgblack** [comment] 2015-09-02 14:51
I've pushed a fix which addresses this problem. Please test it and let me know if the problem is fixed.

**Closed** 2016-02-23 08:34 UTC
Labels: bug
